server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: store
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    propertiers:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:sipag;Mode=Oracle
    username: sa
    password:
